export default{
	"nav":[{
		'img':"../../static/img/nav/01.png",
		'txt':"京东超市"
	},{
		'img':"../../static/img/nav/02.png",
		'txt':"全球购"
	},{
		'img':"../../static/img/nav/03.png",
		'txt':"服装城"
	},{
		'img':"../../static/img/nav/04.png",
		'txt':"京东生鲜"
	},{
		'img':"../../static/img/nav/05.png",
		'txt':"京东到家"
	},{
		'img':"../../static/img/nav/06.png",
		'txt':"充值缴费"
	},{
		'img':"../../static/img/nav/07.png",
		'txt':"领京豆"
	},{
		'img':"../../static/img/nav/08.png",
		'txt':"领券"
	},{
		'img':"../../static/img/nav/09.png",
		'txt':"惠赚钱"
	},{
		'img':"../../static/img/nav/10.png",
		'txt':"物流查询"
	}],
	"navBar":[{
		'img':"../../static/img/product/1.jpg",
		"mon":"1",
		"ago":"81.9"
	},{
		'img':"../../static/img/product/2.png",
		"mon":"298",
		"ago":"600"
	},{
		'img':"../../static/img/product/3.jpg",
		"mon":"134",
		"ago":"200"
	},{
		'img':"../../static/img/product/4.jpg",
		"mon":"145",
		"ago":"200"
	},{
		'img':"../../static/img/product/5.jpg",
		"mon":"13",
		"ago":"356"
	},{
		'img':"../../static/img/product/6.jpg",
		"mon":"800",
		"ago":"1200"
	}],
	"shan":[
	{
		"text":"闪购",
		"txt":"一元好货送你",
		'img':"../../static/img/product/01.jpg"
	},{
		"text":"发现好货",
		"txt":"发现品质生活",
		'img':"../../static/img/product/02.jpg"
	}],
	"paihang1":[
		{
			"text":"排行榜",
			"txt":"实时热卖尖货",
			'img':"../../static/img/product/02.jpg"
		},{
			"text":"会买专辑",
			"txt":"教你买买买",
			'img':"../../static/img/product/phone1.jpg"
		}
	],
	"paihang2":[{
		"text":"新品首发",
		"txt":"三星新品预售",
		'img':"../../static/img/product/phone2.jpg"
	}],
	'body1':[
		{
			"txt":"玩3C",
			"text":"iPhone 7超低价",
			"pink":"疯狂秒杀中",
			'img':"../../static/img/product/05.jpg"
		},{
			"txt":"京东家电",
			"text":"每满1500-100",
			'img':"../../static/img/product/06.jpg"
		}],
	'body2':[{
			"txt":"京东超市",
			"text":"满188减100",
			'img':"../../static/img/product/07.jpg"
		},{
			"txt":"爱家",
			"text":"家装节199-100",
			"pink":"家装节全品类",
			'img':"../../static/img/product/08.jpg"
		}],
	'body3':[{
			"txt":"爱宝宝",
			"text":"爆款低至5折",
			"pink":"超好看",
			'img':"../../static/img/product/b1.jpg"
		},{
			"txt":"爱美丽",
			"text":"美妆0元试用",
			'img':"../../static/img/product/b2.jpg"
		},{
			"txt":"爱吃",
			"text":"低至9.9包邮",
			'img':"../../static/img/product/b3.jpg"
		},{
			"txt":"爱吃",
			"text":"低至9.9包邮",
			"pink":"爆款",
			'img':"../../static/img/product/b4.jpg"
		}],
	'body11':[
		{
			"txt":"全球尖货",
			"text":"进口保健品",
			"pink":"买三免一",
			'img':"../../static/img/product/05.jpg"
		},{
			"txt":"京东精选",
			"text":"每满1500-100",
			'img':"../../static/img/product/06.jpg"
		}],
	'body22':[{
			"txt":"京东超市",
			"text":"满188减100",
			'img':"../../static/img/product/07.jpg"
		},{
			"txt":"爱家",
			"text":"家装节199-100",
			"pink":"家装节全品类",
			'img':"../../static/img/product/08.jpg"
		}],
	'body33':[{
			"txt":"爱宝宝",
			"text":"爆款低至5折",
			"pink":"超好看",
			'img':"../../static/img/product/b1.jpg"
		},{
			"txt":"爱美丽",
			"text":"美妆0元试用",
			'img':"../../static/img/product/b2.jpg"
		},{
			"txt":"爱吃",
			"text":"低至9.9包邮",
			'img':"../../static/img/product/b3.jpg"
		},{
			"txt":"爱吃",
			"text":"低至9.9包邮",
			"pink":"爆款",
			'img':"../../static/img/product/b4.jpg"
		}]	
}